### ISSUE TITLE
css 다크 테마 

### ISSUE THREAD

**Issue by gincheong** [gincheong/Memo#21]
```css
:root {
  --color: #000;
  --background-color: #fff;
}

/* 최상위 태그(html)의 'thememode' attribute가 Dark 이면 아래 변수값 적용 */
[thememode="Dark"] {
  --color: #fff;
  --background-color: #000;
}
```

이렇게 조건에 따른 변수값 저장해 놓고
다른 css 태그쪽에 `color: var(--color);` 처럼 호출하면 됨
