### ISSUE TITLE
SCSS 기능

### ISSUE THREAD

**Issue by gincheong** [gincheong/Memo#33]
```scss
/* SCSS */
.btn {
   display:inline-block; padding:3px 10px; border:1px solid #000;
   &_blue { background-color:blue; border:0; }
   &_yellow { background-color:yellow; border:0; }
}
```

```css
/* CSS */
.btn { display:inline-block; padding:3px 10px; border:1px solid #000; }
.btn_blue { background-color:blue; border:0; }
.btn_yellow { background-color:yellow; border:0; }
```
위의 두 코드가 같음

[출처](https://blog.naver.com/kira4195/221262057145)

**Comment by gincheong** [comment]
정의한 스타일들을 묶어서 한 번에 적용할 수 있게 하는 `@mixin`
```scss
@mixin my-style($font-size) {
  color: #567ace;
  font-weight: bold;
  font-size: $font-size;
}

.my-text {
  @include my-style(15px);
}
```

**Comment by gincheong** [comment]
다른 셀렉터에 정의된 스타일을 불러서 사용할 수 있게 하는 `@extend`

```scss
.text {
  font-weight: bold;
  font-size: 20px;
}

.text-blue {
  @extend .text;
  color: blue;
}

.text-red {
  @extend .text;
  color: red;
}
```
